version: "3.9"
services:
  flask_backend:
    container_name: flask-backend
    build: ../backend
    ports:
      - "5001:5000"  
  node_frontend:
    container_name: node-frontend
    build: ../frontend/PantherExchange
    ports: 
      - "5173:5173"

    
