services:
  backend:
    container_name: flask
    build: ../backend
    ports:
      - "5001:5000"  
  frontend:
    container_name: frontend
    build: ../frontend/PantherExchange
    ports: 
      - "5173:5173"
    depends_on:
      - backend

    
